-- ts_xmgl_bm_kslbk 添加字段  KSLBK_ALIKE_DIFF KSLBK_TYPE_LEVEL
ALTER TABLE 'ts_xmgl_bm_kslbk' ADD COLUMN 'KSLBK_ALIKE_DIFF' varchar(40) NULL
ALTER TABLE 'ts_xmgl_bm_kslbk' ADD COLUMN 'KSLBK_TYPE_LEVEL' varchar(40) NULL

-- TS_WFS_NODEAPPLY_ADMINER   添加字段  S_USER、 S_TDEPT、 S_ODEPT、 S_MTIME、S_FLAF、S_DEPT、S_CMPY、S_ATIME
ALTER TABLE 'TS_WFS_NODEAPPLY_ADMINER' ADD COLUMN 'S_USER' varchar(40) NULL
ALTER TABLE 'TS_WFS_NODEAPPLY_ADMINER' ADD COLUMN 'S_TDEPT' varchar(40) NULL
ALTER TABLE 'TS_WFS_NODEAPPLY_ADMINER' ADD COLUMN 'S_ODEPT' varchar(40) NULL
ALTER TABLE 'TS_WFS_NODEAPPLY_ADMINER' ADD COLUMN 'S_MTIME' varchar(40) NULL
ALTER TABLE 'TS_WFS_NODEAPPLY_ADMINER' ADD COLUMN 'S_FLAF' decimal(4,0) NULL
ALTER TABLE 'TS_WFS_NODEAPPLY_ADMINER' ADD COLUMN 'S_DEPT' varchar(40) NULL
ALTER TABLE 'TS_WFS_NODEAPPLY_ADMINER' ADD COLUMN 'S_CMPY' varchar(40) NULL
ALTER TABLE 'TS_WFS_NODEAPPLY_ADMINER' ADD COLUMN 'S_ATIME' varchar(40) NULL