-- ts_xmgl_sz 添加字段  XM_SZ_TYPENUM
ALTER TABLE `TS_XMGL_SZ` ADD COLUMN `XM_SZ_TYPENUM`  decimal(4,0) NULL;
UPDATE  TS_XMGL_SZ   SET  XM_SZ_TYPENUM = 1  WHERE   XM_SZ_TYPE='进行中';
UPDATE  TS_XMGL_SZ   SET  XM_SZ_TYPENUM = 2  WHERE   XM_SZ_TYPE= '未开启';
UPDATE  TS_XMGL_SZ   SET  XM_SZ_TYPENUM = 3  WHERE   XM_SZ_TYPE= '已结束';

ALTER TABLE `TS_KCGL_UPDATE_ZWDYB` ADD COLUMN `zw_ip` varchar(20) NULL;
ALTER TABLE `TS_KCGL_UPDATE_ZWDYB` ADD COLUMN `zw_desc` varchar(400) NULL;