-- TS_BMSH_PASS表添加BM_TITLE以显示非资格考试名称
ALTER TABLE `TS_BMSH_STAY` ADD COLUMN `BM_TITLE` varchar(80) NULL;
ALTER TABLE `TS_BMSH_PASS` ADD COLUMN `BM_TITLE` varchar(80) NULL;
ALTER TABLE `TS_BMSH_NOPASS` ADD COLUMN `BM_TITLE` varchar(80) NULL;
