-- 增加 ts_jklb_jk 表 JK_DEPT 字段长度
ALTER TABLE `ts_jklb_jk`
MODIFY COLUMN `JK_DEPT`  varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '借考人所在的部门';
UPDATE `sy_comm_menu` SET `MENU_ID`='TS_XMGL_BMSH_SHGZK__icbc', `MENU_NAME`='报名规则管理', `MENU_TYPE`='1', `MENU_INFO`='TS_XMGL_BMSH_SHGZK_QT', `MENU_PID`='TS_BM_GZK__icbc', `MENU_ORDER`='30', `S_FLAG`='1', `S_CMPY`='icbc', `S_PUBLIC`='2', `MENU_ICON`=NULL, `MENU_LEVEL`='4', `CODE_PATH`='3o2Gmj2192FG9KmKmCjMD1bT^0mD41XHHRd1U65LrZDMm^TS_BM_GZK__icbc^TS_XMGL_BMSH_SHGZK__icbc^', `S_MTIME`='2018-02-09 14:15:38:592', `MENU_AREA`='1', `MENU_TIP`=NULL, `MENU_TODO_FLAG`='2', `MENU_TODO_TYPE`=NULL, `DS_NAME`=NULL, `DS_MENU_FLAG`='1', `DS_NORMAL_FLAG`='2', `DS_FOLDER_FLAG`='2', `DS_ICON`=NULL, `MENU_NODE_VIRTUAL`='2', `MENU_OTYPE`='0', `MENU_SCOPE`='63', `MENU_DEV_TYPES`=NULL, `EN_JSON`=NULL WHERE (`MENU_ID`='TS_XMGL_BMSH_SHGZK__icbc');

