package com.rh.core.icbc.pushwxtodo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ToDoServiceSoap", targetNamespace = "http://webservice.iipa/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ToDoServiceSoap {


    /**
     * 
     * @param filterItem
     * @param updateTime
     * @param title
     * @param n
     * @param url
     * @param ownerSSICID
     * @param toDoID
     * @param createTime
     * @param appID
     * @param action
     * @param expireDate
     * @param remark1
     * @param remark3
     * @param remark2
     * @return
     *     returns client.ArrayOfString
     */
    @WebMethod(operationName = "SaveToDo", action = "http://webservice.iipa/SaveToDo")
    @WebResult(name = "SaveToDoResult", targetNamespace = "http://webservice.iipa/")
    @RequestWrapper(localName = "SaveToDo", targetNamespace = "http://webservice.iipa/", className = "client.SaveToDo")
    @ResponseWrapper(localName = "SaveToDoResponse", targetNamespace = "http://webservice.iipa/", className = "client.SaveToDoResponse")
    public ArrayOfString saveToDo(
        @WebParam(name = "n", targetNamespace = "http://webservice.iipa/")
        int n,
        @WebParam(name = "FilterItem", targetNamespace = "http://webservice.iipa/")
        ArrayOfString filterItem,
        @WebParam(name = "OwnerSSICID", targetNamespace = "http://webservice.iipa/")
        ArrayOfString ownerSSICID,
        @WebParam(name = "AppID", targetNamespace = "http://webservice.iipa/")
        ArrayOfInt appID,
        @WebParam(name = "ToDoID", targetNamespace = "http://webservice.iipa/")
        ArrayOfString toDoID,
        @WebParam(name = "Title", targetNamespace = "http://webservice.iipa/")
        ArrayOfString title,
        @WebParam(name = "Url", targetNamespace = "http://webservice.iipa/")
        ArrayOfString url,
        @WebParam(name = "ExpireDate", targetNamespace = "http://webservice.iipa/")
        ArrayOfString expireDate,
        @WebParam(name = "CreateTime", targetNamespace = "http://webservice.iipa/")
        ArrayOfString createTime,
        @WebParam(name = "Action", targetNamespace = "http://webservice.iipa/")
        ArrayOfInt action,
        @WebParam(name = "UpdateTime", targetNamespace = "http://webservice.iipa/")
        ArrayOfString updateTime,
        @WebParam(name = "Remark1", targetNamespace = "http://webservice.iipa/")
        ArrayOfString remark1,
        @WebParam(name = "Remark2", targetNamespace = "http://webservice.iipa/")
        ArrayOfString remark2,
        @WebParam(name = "Remark3", targetNamespace = "http://webservice.iipa/")
        ArrayOfString remark3);

}
